#! /bin/bash

TUNNEL_USER=''
TUNNEL_PORT=''
TUNNEL_HOST=''
SSH_PID=`pgrep -x ssh`
WLAN_ACTIVE=`route | grep 'wlan0' | grep 'G'`
SOCKS_OFF=`cat /etc/privoxy/config | grep $SOCKS_PORT | grep '#'`

if [ -n "$WLAN_ACTIVE" ]; then
 echo "wlan0 is active!"
else
 echo "wlan0 is NOT active!"
fi
 
if [ -z "$SOCKS_OFF" ]; then
 echo "SOCKS forwarding is active!"
else
 echo "SOCKS forwarding is NOT active!"
fi 
 
if [ "$SSH_PID" ] 
then
 killall -e ssh;
fi
sleep 1
su $TUNNEL_USER -c "ssh $TUNNEL_HOST -CND $TUNNEL_PORT &"

if [ -n "$WLAN_ACTIVE" -a -n "$SOCKS_OFF" ]; then
 sed "s,#*\( *forward-socks5.*\),\1," -i /etc/privoxy/config
 echo "activating forwarding"
fi
if [ -z "$WLAN_ACTIVE" -a -z "$SOCKS_OFF" ]; then
 sed "s,\( *forward-socks5.*\),#\1," -i /etc/privoxy/config
 echo "deactivating forwarding"
fi
exit
